// ============================================================
// todólogo.ai — Catálogo maestro de modelos
// Fuente de verdad compartida entre servidor y cliente.
// ============================================================

export type ModelCategory =
  | "texto"
  | "codigo"
  | "razonamiento"
  | "agente"
  | "vision"
  | "imagen"
  | "video"
  | "audio";

/** Categorías generativas (no consumen tokens de texto). */
export const CATEGORIAS_GENERATIVAS = ["imagen", "video", "audio"] as const;

export function esGenerativo(m: AIModel | { categories: ModelCategory[] }): boolean {
  return m.categories.some((c) => (CATEGORIAS_GENERATIVAS as readonly string[]).includes(c));
}

export interface AIModel {
  id: string;
  name: string;
  provider: string;
  license: "propietario" | "abierto";
  categories: ModelCategory[];
  elo: number; // ELO base global
  context: number; // ventana de contexto (tokens)
  maxOutput: number; // salida máxima (tokens)
  priceIn: number; // USD / 1M tokens entrada
  priceOut: number; // USD / 1M tokens salida
  speed: number; // tokens/s medidos en arena
  released: string; // fecha de lanzamiento
  desc: string;
  tags: string[];
  featured?: boolean;
  isNew?: boolean;
  /** Solo modelos generativos (imagen/video/audio): especificación legible. */
  especs?: string;
  /** Solo modelos generativos: precio legible por unidad real (no USD/1M tokens). */
  precioNota?: string;
}

export interface Provider {
  id: string;
  name: string;
  color: string; // clase tailwind del punto de color
  country: string;
  domain: string; // web oficial (para el logotipo y el enlace)
  logo?: string; // ruta local al logotipo oficial (/providers/<id>.png)
}

export const PROVIDERS: Record<string, Provider> = {
  zai: { id: "zai", name: "Z.ai", color: "bg-emerald-400", country: "CN", domain: "z.ai", logo: "/providers/zai.png" },
  anthropic: { id: "anthropic", name: "Anthropic", color: "bg-orange-400", country: "US", domain: "anthropic.com", logo: "/providers/anthropic.png" },
  openai: { id: "openai", name: "OpenAI", color: "bg-teal-400", country: "US", domain: "openai.com", logo: "/providers/openai.png" },
  google: { id: "google", name: "Google DeepMind", color: "bg-amber-400", country: "US", domain: "deepmind.google", logo: "/providers/google.png" },
  qwen: { id: "qwen", name: "Qwen", color: "bg-blue-600", country: "CN", domain: "qwen.ai", logo: "/providers/qwen.png" },
  deepseek: { id: "deepseek", name: "DeepSeek", color: "bg-fuchsia-400", country: "CN", domain: "deepseek.com", logo: "/providers/deepseek.png" },
  microsoft: { id: "microsoft", name: "Microsoft", color: "bg-cyan-400", country: "US", domain: "microsoft.com", logo: "/providers/microsoft.png" },
  yi: { id: "yi", name: "01.AI", color: "bg-pink-400", country: "CN", domain: "01.ai", logo: "/providers/yi.png" },
  xai: { id: "xai", name: "xAI", color: "bg-zinc-200", country: "US", domain: "x.ai", logo: "/providers/xai.png" },
  mistral: { id: "mistral", name: "Mistral AI", color: "bg-red-400", country: "FR", domain: "mistral.ai", logo: "/providers/mistral.png" },
  moonshot: { id: "moonshot", name: "Moonshot AI", color: "bg-purple-400", country: "CN", domain: "moonshot.ai", logo: "/providers/moonshot.png" },
  meta: { id: "meta", name: "Meta", color: "bg-sky-400", country: "US", domain: "meta.com", logo: "/providers/meta.png" },
  cohere: { id: "cohere", name: "Cohere", color: "bg-pink-300", country: "CA", domain: "cohere.com", logo: "/providers/cohere.png" },
  amazon: { id: "amazon", name: "Amazon", color: "bg-yellow-400", country: "US", domain: "aws.amazon.com", logo: "/providers/amazon.png" },
  baidu: { id: "baidu", name: "Baidu", color: "bg-red-300", country: "CN", domain: "baidu.com", logo: "/providers/baidu.png" },
  tencent: { id: "tencent", name: "Tencent", color: "bg-blue-300", country: "CN", domain: "tencent.com", logo: "/providers/tencent.png" },
  bytedance: { id: "bytedance", name: "ByteDance", color: "bg-lime-400", country: "CN", domain: "bytedance.com", logo: "/providers/bytedance.png" },
  minimax: { id: "minimax", name: "MiniMax", color: "bg-rose-300", country: "CN", domain: "minimax.io", logo: "/providers/minimax.png" },
  ai21: { id: "ai21", name: "AI21 Labs", color: "bg-teal-300", country: "IL", domain: "ai21.com", logo: "/providers/ai21.png" },
  ibm: { id: "ibm", name: "IBM", color: "bg-indigo-300", country: "US", domain: "ibm.com", logo: "/providers/ibm.png" },
  nvidia: { id: "nvidia", name: "NVIDIA", color: "bg-green-400", country: "US", domain: "nvidia.com", logo: "/providers/nvidia.png" },
  reka: { id: "reka", name: "Reka AI", color: "bg-orange-300", country: "US", domain: "reka.ai", logo: "/providers/reka.png" },
  tii: { id: "tii", name: "TII", color: "bg-emerald-300", country: "AE", domain: "tii.ae" },
  ai2: { id: "ai2", name: "Allen AI", color: "bg-lime-300", country: "US", domain: "allenai.org", logo: "/providers/ai2.png" },
  bigcode: { id: "bigcode", name: "BigCode", color: "bg-yellow-300", country: "EU", domain: "bigcode-project.org", logo: "/providers/bigcode.png" },
  stepfun: { id: "stepfun", name: "StepFun", color: "bg-violet-300", country: "CN", domain: "stepfun.com", logo: "/providers/stepfun.png" },
  iflytek: { id: "iflytek", name: "iFlytek", color: "bg-cyan-300", country: "CN", domain: "iflytek.com", logo: "/providers/iflytek.png" },
  muse: { id: "muse", name: "Muse AI", color: "bg-yellow-200", country: "US", domain: "muse.ai", logo: "/providers/muse.png" },
  // ── Proveedores generativos (video · imagen · audio) — v1.15.0 ──
  kuaishou: { id: "kuaishou", name: "Kuaishou", color: "bg-orange-400", country: "CN", domain: "kuaishou.com", logo: "/providers/kuaishou.png" },
  runway: { id: "runway", name: "Runway", color: "bg-neutral-400", country: "US", domain: "runwayml.com", logo: "/providers/runway.png" },
  alibaba: { id: "alibaba", name: "Alibaba Tongyi", color: "bg-orange-500", country: "CN", domain: "tongyi.aliyun.com", logo: "/providers/alibaba.png" },
  midjourney: { id: "midjourney", name: "Midjourney", color: "bg-blue-400", country: "US", domain: "midjourney.com", logo: "/providers/midjourney.png" },
  blackforest: { id: "blackforest", name: "Black Forest Labs", color: "bg-stone-400", country: "DE", domain: "bfl.ai", logo: "/providers/blackforest.png" },
  suno: { id: "suno", name: "Suno", color: "bg-violet-400", country: "US", domain: "suno.com", logo: "/providers/suno.png" },
  elevenlabs: { id: "elevenlabs", name: "ElevenLabs", color: "bg-zinc-400", country: "US", domain: "elevenlabs.io", logo: "/providers/elevenlabs.png" },
  sonauto: { id: "sonauto", name: "Sonauto", color: "bg-red-300", country: "US", domain: "sonauto.ai", logo: "/providers/sonauto.png" },
};

export const MODELS: AIModel[] = [
  // ─── Z.ai ────────────────────────────────────────────────
  {
    id: "glm-5.3",
    name: "GLM-5.3",
    provider: "zai",
    license: "abierto",
    categories: ["texto", "codigo", "razonamiento", "agente"],
    elo: 1487,
    context: 400_000,
    maxOutput: 128_000,
    priceIn: 2.5,
    priceOut: 10,
    speed: 95,
    released: "2026-07-28",
    desc: "Buque insignia de Z.ai: razonamiento híbrido, código de nivel agéntico y 400K de contexto. Líder open-weights del arena.",
    tags: ["flagship", "open-weights", "hybrid-reasoning"],
    featured: true,
    isNew: true,
  },
  {
    id: "glm-5.3-flash",
    name: "GLM-5.3-Flash",
    provider: "zai",
    license: "abierto",
    categories: ["texto", "codigo"],
    elo: 1420,
    context: 256_000,
    maxOutput: 64_000,
    priceIn: 0.4,
    priceOut: 1.2,
    speed: 280,
    released: "2026-07-28",
    desc: "La versión ultrarrápida de GLM-5.3: latencia mínima y coste irrisorio para producción a gran escala.",
    tags: ["rápido", "económico", "producción"],
    isNew: true,
  },
  {
    id: "glm-5.3-air",
    name: "GLM-5.3-Air",
    provider: "zai",
    license: "abierto",
    categories: ["texto", "codigo", "razonamiento"],
    elo: 1441,
    context: 320_000,
    maxOutput: 96_000,
    priceIn: 1.1,
    priceOut: 4.4,
    speed: 160,
    released: "2026-07-28",
    desc: "Equilibrio perfecto entre inteligencia y coste: 80% de la calidad del flagship con 25% del coste.",
    tags: ["equilibrado", "open-weights"],
  },
  {
    id: "glm-5-coder",
    name: "GLM-5-Coder",
    provider: "zai",
    license: "abierto",
    categories: ["codigo", "agente"],
    elo: 1478,
    context: 512_000,
    maxOutput: 128_000,
    priceIn: 2.2,
    priceOut: 8.8,
    speed: 150,
    released: "2026-06-14",
    desc: "Especialista en código: refactors masivos, agentes de terminal y repos completos en una sola pasada.",
    tags: ["código", "agentic-coding", "repos"],
    featured: true,
  },
  // ─── Anthropic ───────────────────────────────────────────
  {
    id: "claude-opus-5",
    name: "Claude Opus 5",
    provider: "anthropic",
    license: "propietario",
    categories: ["texto", "codigo", "razonamiento", "agente"],
    elo: 1492,
    context: 500_000,
    maxOutput: 160_000,
    priceIn: 12,
    priceOut: 60,
    speed: 68,
    released: "2026-08-10",
    desc: "El estándar de oro para trabajo profundo: horas de trabajo autónomo, código impecable y razonamiento extendido.",
    tags: ["flagship", "agentic", "reasoning"],
    featured: true,
    isNew: true,
  },
  {
    id: "claude-sonnet-4.9",
    name: "Claude Sonnet 4.9",
    provider: "anthropic",
    license: "propietario",
    categories: ["texto", "codigo", "agente"],
    elo: 1455,
    context: 400_000,
    maxOutput: 128_000,
    priceIn: 3,
    priceOut: 15,
    speed: 135,
    released: "2026-05-02",
    desc: "El caballo de batalla empresarial: calidad casi-Opus a coste medio, ideal para pipelines de producción.",
    tags: ["equilibrado", "producción"],
  },
  {
    id: "claude-haiku-4.5",
    name: "Claude Haiku 4.5",
    provider: "anthropic",
    license: "propietario",
    categories: ["texto", "codigo"],
    elo: 1398,
    context: 300_000,
    maxOutput: 64_000,
    priceIn: 0.9,
    priceOut: 3.6,
    speed: 340,
    released: "2026-04-18",
    desc: "Ultrarrápido y barato sin perder el toque Anthropic: perfecto para chat, clasificación y resumen a escala.",
    tags: ["rápido", "económico"],
  },
  {
    id: "fable-5.1",
    name: "Fable 5.1",
    provider: "anthropic",
    license: "propietario",
    categories: ["texto", "razonamiento", "agente"],
    elo: 1470,
    context: 350_000,
    maxOutput: 100_000,
    priceIn: 8,
    priceOut: 40,
    speed: 82,
    released: "2026-06-30",
    desc: "El modelazo narrativo de Anthropic: prosa impecable, planificación a largo plazo y memoria de personaje sobrehumana.",
    tags: ["escritura", "creativo", "planning"],
    isNew: true,
  },
  // ─── OpenAI ──────────────────────────────────────────────
  {
    id: "gpt-6-astra",
    name: "GPT-6 Astra",
    provider: "openai",
    license: "propietario",
    categories: ["texto", "codigo", "razonamiento", "agente", "vision"],
    elo: 1494,
    context: 1_000_000,
    maxOutput: 200_000,
    priceIn: 15,
    priceOut: 75,
    speed: 75,
    released: "2026-08-22",
    desc: "El modelo más capaz jamás medido en arena: multimodal nativo, 1M de contexto y orquestación de agentes sin parangón.",
    tags: ["flagship", "omni", "multimodal"],
    featured: true,
    isNew: true,
  },
  {
    id: "gpt-6",
    name: "GPT-6",
    provider: "openai",
    license: "propietario",
    categories: ["texto", "codigo", "razonamiento"],
    elo: 1478,
    context: 512_000,
    maxOutput: 128_000,
    priceIn: 10,
    priceOut: 50,
    speed: 90,
    released: "2026-03-11",
    desc: "La referencia estable de OpenAI para empresa: fiable, obedientemente seguro y con ecosistema de tools maduro.",
    tags: ["empresa", "tools"],
  },
  {
    id: "o5-pro",
    name: "o5-pro",
    provider: "openai",
    license: "propietario",
    categories: ["razonamiento", "texto", "codigo"],
    elo: 1485,
    context: 256_000,
    maxOutput: 100_000,
    priceIn: 20,
    priceOut: 80,
    speed: 35,
    released: "2026-02-05",
    desc: "Cadena de pensamiento extrema para matemáticas, ciencia y arquitectura de sistemas. Lento, pero imparable.",
    tags: ["reasoning", "matemáticas", "ciencia"],
  },
  {
    id: "gpt-5.5-mini",
    name: "GPT-5.5 Mini",
    provider: "openai",
    license: "propietario",
    categories: ["texto", "codigo"],
    elo: 1402,
    context: 256_000,
    maxOutput: 64_000,
    priceIn: 0.5,
    priceOut: 1.5,
    speed: 320,
    released: "2026-01-20",
    desc: "Mini pero matón: la mejor relación coste/velocidad del catálogo OpenAI para tareas rutinarias.",
    tags: ["rápido", "económico"],
  },
  // ─── Google ──────────────────────────────────────────────
  // Nota de auditoría (v1.14.0): «Gemini 3.8 Pro» y «Gemini 3.8 Flash» se
  // retiraron del catálogo: Google nunca ha tenido una serie 3.8 y esos dos
  // modelos no existen. En su lugar, el flagship real de la casa.
  {
    id: "gemini-3-pro",
    name: "Gemini 3 Pro",
    provider: "google",
    license: "propietario",
    categories: ["texto", "codigo", "razonamiento", "vision"],
    elo: 1474,
    context: 1_000_000,
    maxOutput: 64_000,
    priceIn: 2.5,
    priceOut: 15,
    speed: 130,
    released: "2025-11-18",
    desc: "El flagship real de Google DeepMind: razonamiento de nivel pensamiento, multimodalidad nativa y 1M de contexto para tragarse repos y vídeos enteros.",
    tags: ["flagship", "multimodal", "contexto-largo"],
  },
  {
    id: "gemma-4-27b",
    name: "Gemma 4 27B",
    provider: "google",
    license: "abierto",
    categories: ["texto", "codigo"],
    elo: 1381,
    context: 128_000,
    maxOutput: 32_000,
    priceIn: 0.3,
    priceOut: 0.6,
    speed: 190,
    released: "2026-03-26",
    desc: "El abierto compacto de Google: corre on-premise con calidad sorprendente para su tamaño.",
    tags: ["open-weights", "on-prem"],
  },
  // ─── Qwen (Alibaba Cloud) ─────────────────────────────────
  {
    id: "qwen3.8-max",
    name: "Qwen3.8-Max",
    provider: "qwen",
    license: "abierto",
    categories: ["texto", "codigo", "razonamiento", "agente"],
    elo: 1466,
    context: 1_000_000,
    maxOutput: 128_000,
    priceIn: 4,
    priceOut: 16,
    speed: 105,
    released: "2026-07-02",
    desc: "El gigante multilingüe de Alibaba: 119 idiomas nativos y núcleo MoE con atención esparsa.",
    tags: ["multilingüe", "MoE", "open-weights"],
    isNew: true,
  },
  {
    id: "qwen3.8-coder-plus",
    name: "Qwen3.8-Coder-Plus",
    provider: "qwen",
    license: "abierto",
    categories: ["codigo", "agente"],
    elo: 1461,
    context: 512_000,
    maxOutput: 128_000,
    priceIn: 2.8,
    priceOut: 11,
    speed: 140,
    released: "2026-07-02",
    desc: "Entrenado con 12T de tokens de código: dominio total de SQL, Rust, Go y DevOps-as-code.",
    tags: ["código", "open-weights"],
  },
  {
    id: "qwen3.8-turbo",
    name: "Qwen3.8-Turbo",
    provider: "qwen",
    license: "abierto",
    categories: ["texto", "codigo"],
    elo: 1418,
    context: 512_000,
    maxOutput: 64_000,
    priceIn: 0.8,
    priceOut: 3.2,
    speed: 260,
    released: "2026-07-02",
    desc: "Turbo de la familia Qwen para tráfico alto con presupuesto contenido.",
    tags: ["rápido", "económico"],
  },
  // ─── DeepSeek ────────────────────────────────────────────
  {
    id: "deepseek-v4-pro",
    name: "DeepSeek V4-Pro",
    provider: "deepseek",
    license: "abierto",
    categories: ["razonamiento", "texto", "codigo", "agente"],
    elo: 1483,
    context: 384_000,
    maxOutput: 128_000,
    priceIn: 3,
    priceOut: 12,
    speed: 78,
    released: "2026-07-15",
    desc: "Razonamiento profundo con MTP y gradiente dinámico: el abierto que desafía a los propietarios en matemáticas.",
    tags: ["reasoning", "MoE", "open-weights"],
    featured: true,
    isNew: true,
  },
  {
    id: "deepseek-v4",
    name: "DeepSeek V4",
    provider: "deepseek",
    license: "abierto",
    categories: ["texto", "codigo", "razonamiento"],
    elo: 1471,
    context: 256_000,
    maxOutput: 96_000,
    priceIn: 1.5,
    priceOut: 6,
    speed: 120,
    released: "2026-07-15",
    desc: "La versión estándar de V4: calidad DeepSeek con el precio más agresivo del top-15.",
    tags: ["económico", "open-weights"],
  },
  {
    id: "deepseek-v4-flash",
    name: "DeepSeek V4-Flash",
    provider: "deepseek",
    license: "abierto",
    categories: ["texto", "codigo"],
    elo: 1416,
    context: 192_000,
    maxOutput: 48_000,
    priceIn: 0.5,
    priceOut: 2,
    speed: 290,
    released: "2026-07-15",
    desc: "Flash de DeepSeek: distilación de V4 para inferencia en tiempo real y edge cloud.",
    tags: ["rápido", "edge"],
  },
  {
    // Lanzada HOY (9 sept 2026): beta API abierta de la iteración V4.1 de la
    // serie Flash — arquitectura nueva, entrada nativa imagen+texto y ~420
    // tok/s reportados. Verificado en internet: ID oficial deepseek-v4.1-flash,
    // prueba interna «expires-on-0910» sobre la V4-Flash de julio.
    id: "deepseek-v4.1-flash",
    name: "DeepSeek V4.1 Flash",
    provider: "deepseek",
    license: "abierto",
    categories: ["texto", "codigo", "vision"],
    elo: 1445,
    context: 256_000,
    maxOutput: 64_000,
    priceIn: 0.6,
    priceOut: 2.4,
    speed: 420,
    released: "2026-09-09",
    desc: "Acaba de aterrizar: la iteración V4.1 de la serie Flash estrena arquitectura con entrada nativa de imagen y texto y ~420 tokens/s — en beta API abierta hasta el 10 de septiembre.",
    tags: ["rápido", "multimodal", "nueva-arquitectura"],
    isNew: true,
  },
  // ─── Microsoft ───────────────────────────────────────────
  {
    id: "phi-4",
    name: "Phi-4",
    provider: "microsoft",
    license: "abierto",
    categories: ["texto", "razonamiento"],
    elo: 1352,
    context: 128_000,
    maxOutput: 32_000,
    priceIn: 0.2,
    priceOut: 0.8,
    speed: 210,
    released: "2025-12-12",
    desc: "El pequeño gigante de Microsoft: textbooks-quality data en 14B parámetros que rinde como modelos 10x mayores.",
    tags: ["SML", "on-prem", "textbooks"],
  },
  {
    id: "phi-4-turbo",
    name: "Phi-4 Turbo",
    provider: "microsoft",
    license: "abierto",
    categories: ["texto", "codigo"],
    elo: 1368,
    context: 128_000,
    maxOutput: 32_000,
    priceIn: 0.3,
    priceOut: 1.2,
    speed: 260,
    released: "2026-02-27",
    desc: "Phi-4 afinado para código y velocidad: ideal para Copilot-like experiences embebidas.",
    tags: ["código", "edge"],
  },
  // ─── 01.AI ───────────────────────────────────────────────
  {
    id: "yi-lighting",
    name: "Yi-Lighting",
    provider: "yi",
    license: "propietario",
    categories: ["texto", "codigo"],
    elo: 1408,
    context: 300_000,
    maxOutput: 64_000,
    priceIn: 0.7,
    priceOut: 2.8,
    speed: 230,
    released: "2026-04-09",
    desc: "01.AI apuesta por la latencia cero: Yi-Lighting ilumina conversaciones largas a 230 tokens/s.",
    tags: ["rápido", "multilingüe"],
  },
  {
    id: "yi-coder-2-34b",
    name: "Yi-Coder 2 34B",
    provider: "yi",
    license: "abierto",
    categories: ["codigo"],
    elo: 1394,
    context: 256_000,
    maxOutput: 64_000,
    priceIn: 0.6,
    priceOut: 2.4,
    speed: 180,
    released: "2026-01-15",
    desc: "El codificador abierto de 01.AI: relleno medio (FIM) de primera clase y soporte de 338 lenguajes.",
    tags: ["código", "FIM", "open-weights"],
  },
  // ─── xAI ─────────────────────────────────────────────────
  {
    id: "grok-4.6",
    name: "Grok 4.6",
    provider: "xai",
    license: "propietario",
    categories: ["texto", "razonamiento", "agente"],
    elo: 1480,
    context: 512_000,
    maxOutput: 128_000,
    priceIn: 10,
    priceOut: 45,
    speed: 85,
    released: "2026-08-01",
    desc: "El provocador: acceso en vivo a X, razonamiento first-principles y cero miedo a temas espinosos.",
    tags: ["realtime", "reasoning"],
    isNew: true,
  },
  {
    id: "grok-4.6-fast",
    name: "Grok 4.6 Fast",
    provider: "xai",
    license: "propietario",
    categories: ["texto", "codigo"],
    elo: 1445,
    context: 256_000,
    maxOutput: 64_000,
    priceIn: 2,
    priceOut: 9,
    speed: 310,
    released: "2026-08-01",
    desc: "Grok en modo cohete: mismo carácter, velocidad de rayo para apps sociales y streaming.",
    tags: ["rápido", "realtime"],
  },
  // ─── Mistral AI ──────────────────────────────────────────
  {
    id: "mistral-large-3",
    name: "Mistral Large 3",
    provider: "mistral",
    license: "propietario",
    categories: ["texto", "codigo", "razonamiento", "agente"],
    elo: 1458,
    context: 384_000,
    maxOutput: 96_000,
    priceIn: 6,
    priceOut: 24,
    speed: 115,
    released: "2026-07-08",
    desc: "La soberanía europea hecha modelo: multilingüe por diseño, soberanía GDPR total y funciones nativas.",
    tags: ["UE", "GDPR", "soberanía"],
    featured: true,
    isNew: true,
  },
  {
    id: "mistral-medium-3.1",
    name: "Mistral Medium 3.1",
    provider: "mistral",
    license: "propietario",
    categories: ["texto", "codigo"],
    elo: 1428,
    context: 256_000,
    maxOutput: 64_000,
    priceIn: 2.7,
    priceOut: 12,
    speed: 130,
    released: "2026-04-22",
    desc: "El trabajo de gama media de Mistral: rendimiento de gran calidad al precio de un mediano.",
    tags: ["equilibrado", "UE"],
  },
  {
    id: "codestral-26",
    name: "Codestral 26",
    provider: "mistral",
    license: "propietario",
    categories: ["codigo"],
    elo: 1452,
    context: 512_000,
    maxOutput: 96_000,
    priceIn: 2.4,
    priceOut: 9.6,
    speed: 160,
    released: "2026-05-19",
    desc: "El especialista en código de Mistral: más de 120 lenguajes, IDE-plugins y FIM quirúrgico.",
    tags: ["código", "FIM", "IDE"],
  },
  {
    id: "devstral-2",
    name: "Devstral 2",
    provider: "mistral",
    license: "abierto",
    categories: ["codigo", "agente"],
    elo: 1449,
    context: 384_000,
    maxOutput: 96_000,
    priceIn: 1.8,
    priceOut: 7.2,
    speed: 145,
    released: "2026-06-11",
    desc: "Diseñado para SWE-agents: resuelve issues reales de GitHub end-to-end y domina terminales.",
    tags: ["agentic-coding", "SWE", "open-weights"],
  },
  {
    id: "mixtral-8x24b",
    name: "Mixtral 8x24B",
    provider: "mistral",
    license: "abierto",
    categories: ["texto"],
    elo: 1389,
    context: 128_000,
    maxOutput: 32_000,
    priceIn: 0.9,
    priceOut: 3.6,
    speed: 175,
    released: "2025-11-03",
    desc: "El clásico MoE que abrió la caja de Pandora: 8 expertos activos de 24B, ahora económico y estable.",
    tags: ["MoE", "open-weights", "clásico"],
  },
  // ─── Moonshot AI ─────────────────────────────────────────
  {
    id: "kimi-k3",
    name: "Kimi K3",
    provider: "moonshot",
    license: "abierto",
    categories: ["texto", "codigo", "agente", "razonamiento"],
    elo: 1476,
    context: 1_000_000,
    maxOutput: 128_000,
    priceIn: 3.2,
    priceOut: 13,
    speed: 98,
    released: "2026-07-20",
    desc: "El rey del contexto: 1M de tokens nativos y lectura ultralarga con comprensión casi perfecta.",
    tags: ["contexto-largo", "open-weights", "agentic"],
    featured: true,
    isNew: true,
  },
  {
    id: "kimi-swarm",
    name: "Kimi Swarm",
    provider: "moonshot",
    license: "abierto",
    categories: ["agente", "codigo", "razonamiento"],
    elo: 1456,
    context: 512_000,
    maxOutput: 128_000,
    priceIn: 4.5,
    priceOut: 18,
    speed: 88,
    released: "2026-08-05",
    desc: "Enjambre multiagente nativo: despliega hasta 32 sub-agentes coordinados en un solo prompt.",
    tags: ["multiagente", "swarm", "open-weights"],
    isNew: true,
  },
  {
    id: "kimi-mini",
    name: "Kimi Mini",
    provider: "moonshot",
    license: "abierto",
    categories: ["texto", "codigo"],
    elo: 1405,
    context: 256_000,
    maxOutput: 64_000,
    priceIn: 0.6,
    priceOut: 2.4,
    speed: 240,
    released: "2026-03-14",
    desc: "Kimi de bolsillo: resumen de documentos largos y chat a coste marginal.",
    tags: ["rápido", "económico"],
  },
  // ─── Meta ────────────────────────────────────────────────
  {
    id: "llama-4.5-maverick",
    name: "Llama 4.5 Maverick",
    provider: "meta",
    license: "abierto",
    categories: ["texto", "codigo", "razonamiento", "vision"],
    elo: 1447,
    context: 1_000_000,
    maxOutput: 96_000,
    priceIn: 2.2,
    priceOut: 8.8,
    speed: 118,
    released: "2026-05-28",
    desc: "El abanderado del open source de Meta: MoE con 17B activos y visión nativa Interleave.",
    tags: ["open-weights", "MoE", "multimodal"],
  },
  {
    id: "llama-4.5-scout",
    name: "Llama 4.5 Scout",
    provider: "meta",
    license: "abierto",
    categories: ["texto", "codigo"],
    elo: 1424,
    context: 512_000,
    maxOutput: 64_000,
    priceIn: 1.1,
    priceOut: 4.4,
    speed: 220,
    released: "2026-05-28",
    desc: "Scout explora donde Maverick no cabe: single-GPU friendly con 10M de contexto claim en roadmap.",
    tags: ["open-weights", "eficiente"],
  },
  // ─── Cohere ──────────────────────────────────────────────
  {
    id: "command-a-2",
    name: "Command A 2.0",
    provider: "cohere",
    license: "propietario",
    categories: ["texto", "agente", "razonamiento"],
    elo: 1443,
    context: 512_000,
    maxOutput: 96_000,
    priceIn: 5,
    priceOut: 20,
    speed: 125,
    released: "2026-04-30",
    desc: "RAG empresarial de precisión quirúrgica: citas verificables y grounding nativo para banca y legal.",
    tags: ["RAG", "empresa", "citas"],
  },
  {
    id: "command-r-plus-2",
    name: "Command R++ 2",
    provider: "cohere",
    license: "propietario",
    categories: ["texto", "codigo"],
    elo: 1414,
    context: 256_000,
    maxOutput: 64_000,
    priceIn: 2.5,
    priceOut: 10,
    speed: 155,
    released: "2025-12-18",
    desc: "La navaja suiza de Cohere para workflows internos: tool-use estable y markdown impecable.",
    tags: ["tools", "empresa"],
  },
  {
    id: "aya-expanse-2-32b",
    name: "Aya Expanse 2 32B",
    provider: "cohere",
    license: "abierto",
    categories: ["texto"],
    elo: 1398,
    context: 128_000,
    maxOutput: 32_000,
    priceIn: 0.8,
    priceOut: 3.2,
    speed: 165,
    released: "2026-01-29",
    desc: "Reina de la multilingüidad: 141 idiomas con matiz cultural, entrenada con data de lingüistas.",
    tags: ["multilingüe", "open-weights"],
  },
  // ─── Amazon ──────────────────────────────────────────────
  {
    id: "nova-premier-2",
    name: "Nova Premier 2",
    provider: "amazon",
    license: "propietario",
    categories: ["texto", "codigo", "razonamiento"],
    elo: 1436,
    context: 512_000,
    maxOutput: 96_000,
    priceIn: 4.5,
    priceOut: 18,
    speed: 112,
    released: "2026-03-05",
    desc: "AWS-native hasta la médula: integración Bedrock, AgentCore y facturación con descuentos por compromiso.",
    tags: ["AWS", "bedrock", "empresa"],
  },
  {
    id: "nova-pro-1.5",
    name: "Nova Pro 1.5",
    provider: "amazon",
    license: "propietario",
    categories: ["texto", "codigo", "vision"],
    elo: 1410,
    context: 300_000,
    maxOutput: 64_000,
    priceIn: 1.8,
    priceOut: 7.2,
    speed: 240,
    released: "2025-12-04",
    desc: "El mediano de Amazon para cargas retail/logística: rápido, barato y con SLA agresivo.",
    tags: ["rápido", "AWS"],
  },
  // ─── China: Baidu / Tencent / ByteDance / MiniMax / StepFun / iFlytek ──
  {
    id: "ernie-5.5",
    name: "ERNIE 5.5",
    provider: "baidu",
    license: "propietario",
    categories: ["texto", "razonamiento", "vision"],
    elo: 1439,
    context: 256_000,
    maxOutput: 64_000,
    priceIn: 3,
    priceOut: 12,
    speed: 120,
    released: "2026-04-15",
    desc: "El buscador que se volvió cerebro: conocimiento enciclopédico en vivo vía Baidu Search.",
    tags: ["conocimiento", "search-live"],
  },
  {
    id: "hunyuan-t2",
    name: "Hunyuan T2",
    provider: "tencent",
    license: "abierto",
    categories: ["texto", "codigo"],
    elo: 1427,
    context: 256_000,
    maxOutput: 64_000,
    priceIn: 1.4,
    priceOut: 5.6,
    speed: 150,
    released: "2026-02-20",
    desc: "Integración nativa con WeChat y el ecosistema Tencent Cloud; modalidad mixta texto+audio.",
    tags: ["WeChat", "open-weights"],
  },
  {
    id: "doubao-2.0-pro",
    name: "Doubao 2.0 Pro",
    provider: "bytedance",
    license: "propietario",
    categories: ["texto", "codigo", "vision"],
    elo: 1434,
    context: 256_000,
    maxOutput: 64_000,
    priceIn: 1.2,
    priceOut: 4.8,
    speed: 260,
    released: "2026-03-19",
    desc: "El motor detrás de TikTok AI: inferencia volcánica a escala de mil millones de usuarios.",
    tags: ["rápido", "escala"],
  },
  {
    id: "minimax-m3",
    name: "MiniMax M3",
    provider: "minimax",
    license: "abierto",
    categories: ["agente", "codigo", "razonamiento"],
    elo: 1441,
    context: 512_000,
    maxOutput: 128_000,
    priceIn: 2,
    priceOut: 8,
    speed: 132,
    released: "2026-06-25",
    desc: "El agente frugal: RL puro para tool-use largo con presupuesto de tokens autofiscalizado.",
    tags: ["agentic", "RL", "open-weights"],
    isNew: true,
  },
  {
    id: "step-3.5",
    name: "Step 3.5",
    provider: "stepfun",
    license: "propietario",
    categories: ["texto", "vision"],
    elo: 1421,
    context: 192_000,
    maxOutput: 48_000,
    priceIn: 1.6,
    priceOut: 6.4,
    speed: 200,
    released: "2026-05-08",
    desc: "StepFun sube la apuesta multimodal: comprensión de documentos complejos con layout nativo.",
    tags: ["multimodal", "documentos"],
  },
  {
    id: "spark-5-max",
    name: "Spark 5.0 Max",
    provider: "iflytek",
    license: "propietario",
    categories: ["texto"],
    elo: 1392,
    context: 128_000,
    maxOutput: 32_000,
    priceIn: 1,
    priceOut: 4,
    speed: 185,
    released: "2026-01-08",
    desc: "El campeón del chino hablado: ASR+TTS integrado y dominio educativo imbatible.",
    tags: ["voz", "educación"],
  },
  // ─── Especialistas & abiertos independientes ─────────────
  {
    id: "jamba-3-large",
    name: "Jamba 3 Large",
    provider: "ai21",
    license: "propietario",
    categories: ["texto", "codigo"],
    elo: 1409,
    context: 512_000,
    maxOutput: 96_000,
    priceIn: 2,
    priceOut: 8,
    speed: 210,
    released: "2026-02-11",
    desc: "Híbrido Mamba-Transformer: memoria constante con contexto largo y factura mínima.",
    tags: ["SSM", "Mamba", "eficiente"],
  },
  {
    id: "granite-4.5-max",
    name: "Granite 4.5 Max",
    provider: "ibm",
    license: "abierto",
    categories: ["texto", "codigo", "agente"],
    elo: 1396,
    context: 256_000,
    maxOutput: 64_000,
    priceIn: 0.9,
    priceOut: 3.6,
    speed: 170,
    released: "2026-03-30",
    desc: "IBM para el sector regulado: hashing verificable de data de entrenamiento y gobernanza watsonx.",
    tags: ["regulado", "gobernanza", "open-weights"],
  },
  {
    id: "nemotron-5-ultra",
    name: "Nemotron 5 Ultra",
    provider: "nvidia",
    license: "abierto",
    categories: ["codigo", "razonamiento", "agente"],
    elo: 1438,
    context: 384_000,
    maxOutput: 96_000,
    priceIn: 2.6,
    priceOut: 10.4,
    speed: 128,
    released: "2026-05-15",
    desc: "NVIDIA optimiza hasta el último kernel: precisiones FP4 nativas y velocidad récord en H100/GB200.",
    tags: ["GPU", "FP4", "open-weights"],
  },
  {
    id: "reka-core-4",
    name: "Reka Core 4",
    provider: "reka",
    license: "propietario",
    categories: ["texto", "vision", "codigo"],
    elo: 1418,
    context: 256_000,
    maxOutput: 64_000,
    priceIn: 3.5,
    priceOut: 14,
    speed: 140,
    released: "2026-04-02",
    desc: "Multimodal de laboratorio pequeño pero ambición gigante: video-understanding de primera clase.",
    tags: ["multimodal", "video"],
  },
  {
    id: "falcon-4-220b",
    name: "Falcon 4 220B",
    provider: "tii",
    license: "abierto",
    categories: ["texto", "razonamiento"],
    elo: 1401,
    context: 192_000,
    maxOutput: 48_000,
    priceIn: 1.5,
    priceOut: 6,
    speed: 105,
    released: "2026-02-14",
    desc: "El halcón de Abu Dhabi: árabe+inglés de élite y licencia abierta sin ataduras.",
    tags: ["árabe", "open-weights"],
  },
  {
    id: "olmo-4-32b",
    name: "OLMo 4 32B",
    provider: "ai2",
    license: "abierto",
    categories: ["texto", "razonamiento"],
    elo: 1372,
    context: 128_000,
    maxOutput: 32_000,
    priceIn: 0.4,
    priceOut: 1.6,
    speed: 160,
    released: "2026-04-24",
    desc: "Transparencia radical: data, código y checkpoints 100% públicos. El modelo de los investigadores.",
    tags: ["open-science", "auditado"],
  },
  {
    id: "starcoder-3-15b",
    name: "StarCoder 3 15B",
    provider: "bigcode",
    license: "abierto",
    categories: ["codigo"],
    elo: 1366,
    context: 160_000,
    maxOutput: 32_000,
    priceIn: 0.3,
    priceOut: 1.2,
    speed: 195,
    released: "2025-12-09",
    desc: "El open source comunitario para código: 80+ lenguajes, entrenado con The Stack v3 opt-out respetado.",
    tags: ["código", "comunidad", "open-weights"],
  },
  // ─── Muse AI ──────────────────────────────────────────────
  {
    id: "muse-spark-1.3",
    name: "Muse Spark 1.3",
    provider: "muse",
    license: "propietario",
    categories: ["texto", "razonamiento"],
    elo: 1424,
    context: 220_000,
    maxOutput: 64_000,
    priceIn: 1.8,
    priceOut: 6.4,
    speed: 150,
    released: "2026-06-19",
    desc: "El modelo creativo de moda: escritura con voz propia, brainstorming sinfónico y razonamiento cotidiano brillante. El favorito de los guionistas.",
    tags: ["creativo", "escritura", "brainstorming"],
    isNew: true,
    featured: true,
  },

  // ════════════════════════════════════════════════════════════
  // Modelos generativos — v1.15.0 (verificados a 9 sept 2026)
  // Vídeo · Imagen · Audio. Precios por unidad real (segundo o
  // imagen), no por millón de tokens: ver `precioNota`.
  // ════════════════════════════════════════════════════════════

  // ─── Vídeo ───────────────────────────────────────────────
  {
    id: "seedance-2.5",
    name: "Seedance 2.5",
    provider: "bytedance",
    license: "propietario",
    categories: ["video"],
    elo: 1489,
    context: 0,
    maxOutput: 0,
    priceIn: 0,
    priceOut: 0.056,
    speed: 0,
    released: "2026-06-23",
    desc: "El rey del vídeo multi-plano: tomas de hasta 30 segundos con audio nativo, hasta 50 referencias y salida 4K. El estándar de la industria para anuncios y cortos.",
    tags: ["vídeo", "4K", "audio-nativo", "referencias"],
    featured: true,
    isNew: true,
    especs: "4K · hasta 30 s · audio nativo · 50 referencias",
    precioNota: "≈ $0.056 / s de vídeo",
  },
  {
    id: "veo-3.1",
    name: "Veo 3.1",
    provider: "google",
    license: "propietario",
    categories: ["video"],
    elo: 1481,
    context: 0,
    maxOutput: 0,
    priceIn: 0,
    priceOut: 0.4,
    speed: 0,
    released: "2026-05-20",
    desc: "El vídeo con mejor realismo físico y atmosférico: escenas al aire libre impecables y audio nativo sincronizado. Capa Fast disponible para iteración rápida.",
    tags: ["vídeo", "realismo", "audio-nativo"],
    featured: true,
    especs: "1080p · 8 s · audio nativo · capa Fast",
    precioNota: "≈ $0.40 / s (Fast $0.15)",
  },
  {
    id: "sora-2",
    name: "Sora 2",
    provider: "openai",
    license: "propietario",
    categories: ["video"],
    elo: 1474,
    context: 0,
    maxOutput: 0,
    priceIn: 0,
    priceOut: 0.1,
    speed: 0,
    released: "2025-09-30",
    desc: "El pionero del realismo cinematográfico. Su API se retira el 24 de septiembre de 2026: OpenAI empuja la migración hacia la nueva generación de sus estudios.",
    tags: ["vídeo", "cinematográfico", "retirada-2026"],
    especs: "1080p · 10-15 s · audio nativo",
    precioNota: "≈ $0.10 / s de vídeo",
  },
  {
    id: "kling-3.0-turbo",
    name: "Kling 3.0 Turbo",
    provider: "kuaishou",
    license: "propietario",
    categories: ["video"],
    elo: 1458,
    context: 0,
    maxOutput: 0,
    priceIn: 0,
    priceOut: 0.075,
    speed: 0,
    released: "2026-05-06",
    desc: "El especialista en imagen-a-vídeo cinematográfico: movimiento de cámara coherente y física creíble, con la mejor relación calidad/segundo del mercado.",
    tags: ["vídeo", "image-to-video", "cine"],
    especs: "1080p · 5-10 s · Turbo",
    precioNota: "≈ $0.075 / s de vídeo",
  },
  {
    id: "runway-gen-4.5",
    name: "Runway Gen-4.5",
    provider: "runway",
    license: "propietario",
    categories: ["video"],
    elo: 1442,
    context: 0,
    maxOutput: 0,
    priceIn: 0,
    priceOut: 0.05,
    speed: 0,
    released: "2026-06-30",
    desc: "La herramienta del cineasta profesional: control de personajes, referencias visuales consistentes y un ecosistema de edición que ningún rival iguala.",
    tags: ["vídeo", "post-producción", "referencias"],
    especs: "1080p · 5-10 s · control de personaje",
    precioNota: "≈ $0.05 / s (créditos)",
  },
  {
    id: "wan-3.0",
    name: "Wan 3.0",
    provider: "alibaba",
    license: "abierto",
    categories: ["video"],
    elo: 1408,
    context: 0,
    maxOutput: 0,
    priceIn: 0,
    priceOut: 0.02,
    speed: 0,
    released: "2026-08-21",
    desc: "Los pesos abiertos del vídeo: la alternativa autoalojable de Alibaba que iguala a los cierres de su generación en tomas cortas. Favorito de la comunidad.",
    tags: ["vídeo", "open-weights", "autoalojable"],
    especs: "720p-1080p · 5 s · open-weights",
    precioNota: "≈ $0.02 / s o autoalojado",
  },
  {
    id: "grok-imagine-2.0",
    name: "Grok Imagine 2.0",
    provider: "xai",
    license: "propietario",
    categories: ["video", "imagen"],
    elo: 1436,
    context: 0,
    maxOutput: 0,
    priceIn: 0,
    priceOut: 0.03,
    speed: 0,
    released: "2026-05-12",
    desc: "El generador multimodal de xAI: de texto a imagen y de imagen a vídeo con la misma semilla, integrado en X. El más rápido para contenido viral.",
    tags: ["vídeo", "imagen", "multimodal"],
    especs: "720p · 6 s · híbrido imagen+vídeo",
    precioNota: "≈ $0.03 / s de vídeo",
  },

  // ─── Imagen ──────────────────────────────────────────────
  {
    id: "gpt-image-2.5-sunburst",
    name: "GPT-Image-2.5 Sunburst",
    provider: "openai",
    license: "propietario",
    categories: ["imagen"],
    elo: 1496,
    context: 0,
    maxOutput: 0,
    priceIn: 0,
    priceOut: 0.25,
    speed: 0,
    released: "2026-09-08",
    desc: "La capa premium de ChatGPT Images 2.5: el modelo más capaz de OpenAI para generación y edición, con control fino en flujos visuales exigentes y textos impecables.",
    tags: ["imagen", "premium", "edición-fina"],
    featured: true,
    isNew: true,
    especs: "Hasta 4K · 5 niveles de calidad · edición fina",
    precioNota: "≈ $0.25 / imagen premium",
  },
  {
    id: "gpt-image-2.5-flare",
    name: "GPT-Image-2.5 Flare",
    provider: "openai",
    license: "propietario",
    categories: ["imagen"],
    elo: 1488,
    context: 0,
    maxOutput: 0,
    priceIn: 0,
    priceOut: 0.08,
    speed: 0,
    released: "2026-09-08",
    desc: "La capa por defecto de GPT Image 2.5: misma calidad, edición y mejoras de velocidad que Sunburst, hasta un 50% más barata. La nueva referencia de coste/calidad.",
    tags: ["imagen", "equilibrado", "económico"],
    isNew: true,
    especs: "Hasta 4K · 5 niveles de calidad",
    precioNota: "≈ $0.08 / imagen",
  },
  {
    id: "gpt-image-2.5-instant",
    name: "GPT-Image-2.5 Instant",
    provider: "openai",
    license: "propietario",
    categories: ["imagen"],
    elo: 1470,
    context: 0,
    maxOutput: 0,
    priceIn: 0,
    priceOut: 0.03,
    speed: 0,
    released: "2026-09-08",
    desc: "La capa ultrarrápida de ChatGPT Images 2.5: bocetos e iteraciones en segundos dentro del chat, ideal para explorar ideas antes de rematar en Sunburst.",
    tags: ["imagen", "rápido", "bocetos"],
    isNew: true,
    especs: "1024px · generación en segundos",
    precioNota: "≈ $0.03 / imagen",
  },
  {
    id: "gpt-image-2",
    name: "GPT Image 2",
    provider: "openai",
    license: "propietario",
    categories: ["imagen"],
    elo: 1466,
    context: 0,
    maxOutput: 0,
    priceIn: 0,
    priceOut: 0.1,
    speed: 0,
    released: "2026-04-30",
    desc: "El buque insignia anterior de OpenAI, aún en catálogo y en producción: generación y edición por API con el contrato estable que las empresas ya integraron.",
    tags: ["imagen", "api-estable", "producción"],
    especs: "1536px · edición por API",
    precioNota: "≈ $0.10 / imagen",
  },
  {
    id: "nano-banana-pro",
    name: "Nano Banana Pro",
    provider: "google",
    license: "propietario",
    categories: ["imagen"],
    elo: 1492,
    context: 0,
    maxOutput: 0,
    priceIn: 0,
    priceOut: 0.12,
    speed: 0,
    released: "2026-05-28",
    desc: "El campeón de renderizado de texto dentro de imagen: carteles, interfaces y tipografía impecable, con edición conversacional dentro de Gemini.",
    tags: ["imagen", "texto-en-imagen", "edición"],
    featured: true,
    especs: "Hasta 2K · texto perfecto · Gemini",
    precioNota: "≈ $0.12 / imagen",
  },
  {
    id: "nano-banana-2",
    name: "Nano Banana 2",
    provider: "google",
    license: "propietario",
    categories: ["imagen"],
    elo: 1484,
    context: 0,
    maxOutput: 0,
    priceIn: 0,
    priceOut: 0.04,
    speed: 0,
    released: "2026-05-28",
    desc: "El generador del día a día de Google: rápido, barato y sorprendentemente consistente en edición. El favorito de los creadores para iterar sin pensar en el coste.",
    tags: ["imagen", "rápido", "edición"],
    especs: "1024-2048px · edición conversacional",
    precioNota: "≈ $0.04 / imagen",
  },
  {
    id: "seedream-5.0",
    name: "Seedream 5.0",
    provider: "bytedance",
    license: "propietario",
    categories: ["imagen"],
    elo: 1480,
    context: 0,
    maxOutput: 0,
    priceIn: 0,
    priceOut: 0.03,
    speed: 0,
    released: "2026-07-22",
    desc: "La potencia estética de ByteDance: imágenes expresivas con acabado pulido y el mejor renderizado de texto asiático del mercado, hasta 4K.",
    tags: ["imagen", "estético", "4K"],
    isNew: true,
    especs: "Hasta 4K · texto multilingüe",
    precioNota: "≈ $0.03 / imagen",
  },
  {
    id: "midjourney-v8.2",
    name: "Midjourney V8.2",
    provider: "midjourney",
    license: "propietario",
    categories: ["imagen"],
    elo: 1462,
    context: 0,
    maxOutput: 0,
    priceIn: 0,
    priceOut: 0.08,
    speed: 0,
    released: "2026-06-10",
    desc: "El estándar artístico de la generación de imágenes: estética unmistakable, luz pintórica y un editor web que por fin acompaña a la generación.",
    tags: ["imagen", "artístico", "editor-web"],
    especs: "Hasta 2K · estética premium",
    precioNota: "≈ $0.08 / imagen (suscripción)",
  },
  {
    id: "flux-2-pro",
    name: "FLUX.2 [pro]",
    provider: "blackforest",
    license: "propietario",
    categories: ["imagen"],
    elo: 1455,
    context: 0,
    maxOutput: 0,
    priceIn: 0,
    priceOut: 0.025,
    speed: 0,
    released: "2026-03-18",
    desc: "La API profesional de Black Forest Labs: fotorrealismo quirúrgico, ControlNets de segunda generación y la latencia más baja del top de imagen.",
    tags: ["imagen", "fotorrealismo", "API"],
    especs: "2048px · ControlNets v2",
    precioNota: "≈ $0.025 / imagen",
  },
  {
    id: "mai-image-2.6-preview",
    name: "MAI-Image 2.6 Preview",
    provider: "microsoft",
    license: "propietario",
    categories: ["imagen"],
    elo: 1418,
    context: 0,
    maxOutput: 0,
    priceIn: 0,
    priceOut: 0.02,
    speed: 0,
    released: "2026-08-19",
    desc: "La apuesta generativa de Microsoft, en vista previa privada por invitación desde agosto: fuerte en diagramas, capturas de producto y escenas de oficina.",
    tags: ["imagen", "vista-previa", "empresarial"],
    isNew: true,
    especs: "1024-2048px · vista previa privada",
    precioNota: "Por invitación",
  },

  // ─── Audio ───────────────────────────────────────────────
  {
    id: "suno-5.5",
    name: "Suno v5.5",
    provider: "suno",
    license: "propietario",
    categories: ["audio"],
    elo: 1490,
    context: 0,
    maxOutput: 0,
    priceIn: 0,
    priceOut: 0.02,
    speed: 0,
    released: "2026-07-30",
    desc: "El mejor generador de canciones completas: voces naturales imposibles de distinguir, cobertura de géneros enciclopédica y letras que riman de verdad.",
    tags: ["música", "voces", "canciones"],
    featured: true,
    isNew: true,
    especs: "Canciones completas · hasta 8 min · stems",
    precioNota: "≈ $0.02 / canción",
  },
  {
    id: "eleven-music",
    name: "ElevenLabs Music",
    provider: "elevenlabs",
    license: "propietario",
    categories: ["audio"],
    elo: 1472,
    context: 0,
    maxOutput: 0,
    priceIn: 0,
    priceOut: 0.8,
    speed: 0,
    released: "2026-04-02",
    desc: "La música con la firma de voz de ElevenLabs: mezcla limpia, separación instrumental quirúrgica y la mejor integración con doblaje y locución del mercado.",
    tags: ["música", "mezcla", "doblaje"],
    especs: "Hasta 3 min · mezcla profesional",
    precioNota: "≈ $0.80 / minuto",
  },
  {
    id: "lyria-3-pro",
    name: "Lyria 3 Pro",
    provider: "google",
    license: "propietario",
    categories: ["audio"],
    elo: 1468,
    context: 0,
    maxOutput: 0,
    priceIn: 0,
    priceOut: 0.06,
    speed: 0,
    released: "2026-03-14",
    desc: "El motor musical de Google DeepMind con canto nativo: integrado en Flow y Veo para bandas sonoras sincronizadas con el plano, no pegadas encima.",
    tags: ["música", "canto", "banda-sonora"],
    especs: "Banda sonora sincronizada · canto nativo",
    precioNota: "≈ $0.06 / minuto",
  },
  {
    id: "minimax-music-2.5",
    name: "MiniMax Music 2.5",
    provider: "minimax",
    license: "propietario",
    categories: ["audio"],
    elo: 1444,
    context: 0,
    maxOutput: 0,
    priceIn: 0,
    priceOut: 0.01,
    speed: 0,
    released: "2026-02-25",
    desc: "La alternativa económica que no suena económica: canciones con voz en español y chino a precio de risa, ideal para volumen alto de contenido.",
    tags: ["música", "económico", "multilingüe"],
    especs: "Hasta 4 min · es/zh nativo",
    precioNota: "≈ $0.01 / canción",
  },
  {
    id: "sonauto-v3",
    name: "Sonauto V3",
    provider: "sonauto",
    license: "abierto",
    categories: ["audio"],
    elo: 1402,
    context: 0,
    maxOutput: 0,
    priceIn: 0,
    priceOut: 0.005,
    speed: 0,
    released: "2026-04-02",
    desc: "El generador comunitario de música: pesos abiertos, control por stems y la comunidad más activa en Remix. La opción de los que quieren tocar el modelo.",
    tags: ["música", "open-weights", "stems"],
    especs: "Pesos abiertos · control por stems",
    precioNota: "≈ $0.005 / canción",
  },

  // ─── Refuerzos de texto (v1.20.0): el catálogo alcanza los 64 modelos que
  // exige la Copa Todólogo XXL — antes del sorteo garantizado, una copa de 64
  // no tenía catálogo suficiente y el cuadro nacía con huecos. ───
  {
    id: "mistral-large-3.1",
    name: "Mistral Large 3.1",
    provider: "mistral",
    license: "propietario",
    categories: ["texto", "razonamiento", "agente"],
    elo: 1247,
    context: 256_000,
    maxOutput: 64_000,
    priceIn: 2.2,
    priceOut: 6.5,
    speed: 88,
    released: "2026-08-14",
    desc: "El regreso europeo: Multiflow 2 en el decodificador, razonamiento bilingüe franco-español impecable y la mejor relación precio/agencia de Europa.",
    tags: ["europa", "agente", "multilingüe"],
    isNew: true,
  },
  {
    id: "codestral-26-air",
    name: "Codestral 26 Air",
    provider: "mistral",
    license: "propietario",
    categories: ["codigo", "texto"],
    elo: 1226,
    context: 192_000,
    maxOutput: 48_000,
    priceIn: 0.9,
    priceOut: 2.8,
    speed: 165,
    released: "2026-08-14",
    desc: "El especialista en código de Mistral, reentrenado con repositorios de 2026: fill-in-the-middle líder, diffs quirúrgicos y 40+ lenguajes nativos.",
    tags: ["código", "FIM", "rápido"],
    isNew: true,
  },
  {
    id: "command-a-2-light",
    name: "Command A2 Light",
    provider: "cohere",
    license: "propietario",
    categories: ["texto", "agente"],
    elo: 1210,
    context: 256_000,
    maxOutput: 64_000,
    priceIn: 2.0,
    priceOut: 6.0,
    speed: 92,
    released: "2026-08-21",
    desc: "La apuesta RAG-first de Cohere: citas verificables por párrafo, herramientas empresariales nativas y el mejor castellano comercial del catálogo.",
    tags: ["RAG", "empresas", "citas"],
    isNew: true,
  },
  {
    id: "nova-pro-2",
    name: "Nova Pro 2",
    provider: "amazon",
    license: "propietario",
    categories: ["texto", "razonamiento"],
    elo: 1194,
    context: 300_000,
    maxOutput: 64_000,
    priceIn: 1.6,
    priceOut: 4.8,
    speed: 105,
    released: "2026-08-28",
    desc: "La segunda generación de la familia Nova: contexto de 300K, documentos larguísimos sin alucinar y latencia constante bajo carga extrema.",
    tags: ["contexto-largo", "documentos", "aws"],
    isNew: true,
  },
  {
    id: "nemotron-5-super",
    name: "Nemotron 5 Super",
    provider: "nvidia",
    license: "abierto",
    categories: ["texto", "codigo", "razonamiento"],
    elo: 1181,
    context: 128_000,
    maxOutput: 32_000,
    priceIn: 0.7,
    priceOut: 1.9,
    speed: 140,
    released: "2026-08-21",
    desc: "NVIDIA vuelve al arena con pesos abiertos destilados de su jefe de razonamiento: SQL y análisis tabular de élite y un pipeline de síntesis de datos propio.",
    tags: ["open-weights", "sql", "síntesis"],
    isNew: true,
  },
  {
    id: "granite-5-max",
    name: "Granite 5 Max",
    provider: "ibm",
    license: "abierto",
    categories: ["texto", "agente"],
    elo: 1167,
    context: 128_000,
    maxOutput: 32_000,
    priceIn: 0.5,
    priceOut: 1.4,
    speed: 150,
    released: "2026-08-28",
    desc: "El modelo corporativo por excelencia: gobernanza auditiva, huella de carbono declarada por token y cumplimiento normativo nativo para sectores regulados.",
    tags: ["gobernanza", "empresas", "open-weights"],
    isNew: true,
  },
  {
    id: "step-3.5-max",
    name: "Step 3.5 Max",
    provider: "stepfun",
    license: "propietario",
    categories: ["texto", "razonamiento"],
    elo: 1156,
    context: 256_000,
    maxOutput: 48_000,
    priceIn: 0.8,
    priceOut: 2.2,
    speed: 118,
    released: "2026-08-14",
    desc: "El poeta de StepFun: prosa creativa en cinco idiomas, estructura narrativa de largo aliento y una sensibilidad estética rara en el tramo medio del ranking.",
    tags: ["creativo", "prosa", "multilingüe"],
    isNew: true,
  },
  {
    id: "spark-x2",
    name: "Spark X2",
    provider: "iflytek",
    license: "propietario",
    categories: ["texto", "razonamiento"],
    elo: 1141,
    context: 128_000,
    maxOutput: 32_000,
    priceIn: 0.4,
    priceOut: 1.1,
    speed: 172,
    released: "2026-08-28",
    desc: "El tutor paciente de iFlytek: pedagogía socrática paso a paso, ejercicios adaptativos y el mejor costo por estudiante del catálogo educativo.",
    tags: ["educación", "socrático", "económico"],
    isNew: true,
  },
];

// ─── Utilidades ─────────────────────────────────────────────

export function getModel(id: string): AIModel | undefined {
  return MODELS.find((m) => m.id === id);
}

export function providerOf(m: AIModel): Provider {
  return PROVIDERS[m.provider];
}

export const CATEGORIES: { id: ModelCategory | "todas"; label: string }[] = [
  { id: "todas", label: "Todas" },
  { id: "texto", label: "Texto" },
  { id: "codigo", label: "Código" },
  { id: "razonamiento", label: "Razonamiento" },
  { id: "agente", label: "Agente" },
  { id: "vision", label: "Visión" },
  { id: "imagen", label: "Imagen" },
  { id: "video", label: "Vídeo" },
  { id: "audio", label: "Audio" },
];

export function formatContext(n: number): string {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(n % 1_000_000 === 0 ? 0 : 1)}M`;
  return `${Math.round(n / 1000)}K`;
}

